markdown: GFM
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      render_with_liquid: false # Avoids using liquid inside pages - only works on jekyll > 4
exclude: ["src"]