name: Update docs

on:
  push:
    branches: ["master"]
  repository_dispatch:
    types: [push]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  update_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up environment
        uses: michijs/.github/.github/actions/setup@main

      - name: Install dependencies
        uses: michijs/.github/.github/actions/install@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Git configuration
        uses: michijs/.github/.github/actions/set-git-config-github-actions@main

      - name: Fetch npm Versions
        id: fetch_versions
        run: |
          VERSIONS=$(bunx npm show @michijs/michijs versions --json)
          FILTERED_VERSIONS=$(echo "$VERSIONS" | jq -r 'map(select(. | test("beta|rc") | not)) | join(" ")')
          echo "VERSIONS=$FILTERED_VERSIONS" >> $GITHUB_ENV

      - name: Clean and retrieve unique READMEs
        id: fetch_readmes
        run: |
          mkdir -p jekyll-src/tmp
      
          # Remove old versioned README files
          find jekyll-src -maxdepth 1 -type f -name 'v*.md' -exec rm -f {} +
      
          unique_hashes=()
      
          for version in $VERSIONS; do
            url="https://raw.githubusercontent.com/michijs/michijs/v$version/README.md"
            tmp_file="jekyll-src/tmp/v$version.md"
            wget -q -O "$tmp_file" "$url"
      
            hash=$(sha256sum "$tmp_file" | awk '{print $1}')
            is_unique=true
      
            for existing_hash in "${unique_hashes[@]}"; do
              if [[ "$hash" == "$existing_hash" ]]; then
                is_unique=false
                break
              fi
            done
      
            if $is_unique; then
              unique_hashes+=("$hash")
              cp "$tmp_file" "jekyll-src/v$version.md"
            fi
          done
      
          # Download the master branch README as Next.md
          wget -q -O jekyll-src/Next.md https://raw.githubusercontent.com/michijs/michijs/master/README.md
      
          rm -r jekyll-src/tmp


      - name: Commit changes
        uses: michijs/.github/.github/actions/commit-if-changes@main
        with:
          message: "Readme update"

      - name: Push changes
        uses: michijs/.github/.github/actions/pull-and-push@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: michijs/.github/.github/actions/run@main
        with:
          command: build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.245.0
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems

      - name: Build with Jekyll
        run: |
          bundle exec jekyll build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
