name: Update docs

on:
  push:
    branches: ["master"]
  repository_dispatch:
    types: [push]
  workflow_dispatch:

jobs:
  copy-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2
          
      - name: Git configuration
        uses: michijs/.github/.github/actions/set-git-config-github-actions@main

      - name: Import README.md file
        shell: bash
        run: wget -O README.md https://raw.githubusercontent.com/michijs/michijs/new-observers-v2/README.md

      - name: Commit changes
        uses: michijs/.github/.github/actions/commit-if-changes@main
        with:
          message: "Readme update"

      - name: Push changes
        uses: michijs/.github/.github/actions/pull-and-push@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
